/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class leo_modules_sat_solver_PicoSAT__ */

#ifndef _Included_leo_modules_sat_solver_PicoSAT__
#define _Included_leo_modules_sat_solver_PicoSAT__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     leo_modules_sat_solver_PicoSAT__
 * Method:    picosat_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_leo_modules_sat_1solver_PicoSAT_00024_picosat_1version
  (JNIEnv *, jobject);

/*
 * Class:     leo_modules_sat_solver_PicoSAT__
 * Method:    picosat_api_version
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_leo_modules_sat_1solver_PicoSAT_00024_picosat_1api_1version
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
