/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class leo_modules_sat_solver_PicoSAT */

#ifndef _Included_leo_modules_sat_solver_PicoSAT
#define _Included_leo_modules_sat_solver_PicoSAT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     leo_modules_sat_solver_PicoSAT
 * Method:    picosat_init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_leo_modules_sat_1solver_PicoSAT_picosat_1init
  (JNIEnv *, jobject);

/*
 * Class:     leo_modules_sat_solver_PicoSAT
 * Method:    picosat_enable_trace_generation
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_leo_modules_sat_1solver_PicoSAT_picosat_1enable_1trace_1generation
  (JNIEnv *, jobject, jlong);

/*
 * Class:     leo_modules_sat_solver_PicoSAT
 * Method:    picosat_reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_leo_modules_sat_1solver_PicoSAT_picosat_1reset
  (JNIEnv *, jobject, jlong);

/*
 * Class:     leo_modules_sat_solver_PicoSAT
 * Method:    picosat_res
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_leo_modules_sat_1solver_PicoSAT_picosat_1res
  (JNIEnv *, jobject, jlong);

/*
 * Class:     leo_modules_sat_solver_PicoSAT
 * Method:    picosat_inc_max_var
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_leo_modules_sat_1solver_PicoSAT_picosat_1inc_1max_1var
  (JNIEnv *, jobject, jlong);

/*
 * Class:     leo_modules_sat_solver_PicoSAT
 * Method:    picosat_add
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_leo_modules_sat_1solver_PicoSAT_picosat_1add
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     leo_modules_sat_solver_PicoSAT
 * Method:    picosat_sat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_leo_modules_sat_1solver_PicoSAT_picosat_1sat
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
