/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class leo_modules_sat_solver_PicoSAT_UNSAT__ */

#ifndef _Included_leo_modules_sat_solver_PicoSAT_UNSAT__
#define _Included_leo_modules_sat_solver_PicoSAT_UNSAT__
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
